- name: Update and upgrade CentOS machines
  hosts: centos
  become: yes
  tasks:
    - name: Ensure yum packages are up to date
      yum:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Clean yum cache
      command: yum clean all
      when: ansible_facts['os_family'] == "RedHat"
