---
- hosts: all
  become: yes
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 packages
    apt:
      name: apache2

  - name: add PHP support for apache
    apt:
      name: libapache2-mod-php
